# Generated by Django 4.2.20 on 2025-04-27 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("course_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "course_code",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("grading_details", models.JSONField(blank=True, null=True)),
                ("office_hours", models.TextField(blank=True, null=True)),
                ("image_url", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="taught_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("exam_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("Midterm", "Midterm"),
                            ("Final", "Final"),
                            ("Resit", "Resit"),
                            ("Research", "Research"),
                            ("Quiz", "Quiz"),
                        ],
                        max_length=10,
                    ),
                ),
                ("exam_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "exam_datetime",
                    models.DateTimeField(blank=True, db_column="exam_date", null=True),
                ),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("details", models.TextField(blank=True, null=True)),
                ("rules", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Scheduled", "Scheduled"),
                            ("Not Graded", "Not Graded"),
                            ("Graded", "Graded"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Scheduled",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="sis.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("instructor", "Instructor"),
                            ("secretary", "Secretary"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "student_id_profile",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "employee_id_profile",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "office_location",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "announcement_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "file_attachment_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="sis.course",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posted_announcements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                ("grade_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "letter_grade",
                    models.CharField(
                        choices=[
                            ("AA", "AA"),
                            ("BA", "BA"),
                            ("BB", "BB"),
                            ("CB", "CB"),
                            ("CC", "CC"),
                            ("DC", "DC"),
                            ("DD", "DD"),
                            ("FD", "FD"),
                            ("FF", "FF"),
                            ("DZ", "DZ"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "numeric_grade",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("is_resit_eligible", models.BooleanField(default=False)),
                (
                    "resit_request_status",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("Requested", "Requested"),
                            ("Approved", "Approved"),
                            ("Denied", "Denied"),
                        ],
                        default="None",
                        max_length=10,
                    ),
                ),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="sis.exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"unique_together": {("student", "exam")},},
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                ("enrollment_id", models.AutoField(primary_key=True, serialize=False)),
                ("enrollment_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students_enrolled",
                        to="sis.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"unique_together": {("student", "course")},},
        ),
    ]
